// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGhN5AwCm_Xa2idH91l_uqHUqBbnjxjls',
    appId: '1:379510913390:web:3ba30a046a2ff8f5f0697f',
    messagingSenderId: '379510913390',
    projectId: 'portfolio-f4327',
    authDomain: 'portfolio-f4327.firebaseapp.com',
    storageBucket: 'portfolio-f4327.firebasestorage.app',
    measurementId: 'G-LNWBWXG48G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANwvdFR5xJK3o5hUE9FBdl-JeU-fTkw9w',
    appId: '1:379510913390:android:e3b95cc1006db81df0697f',
    messagingSenderId: '379510913390',
    projectId: 'portfolio-f4327',
    storageBucket: 'portfolio-f4327.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9QZn3Ws6lZkeFYTbnZzk8syJgI2WBEe0',
    appId: '1:379510913390:ios:10d266b83e598e87f0697f',
    messagingSenderId: '379510913390',
    projectId: 'portfolio-f4327',
    storageBucket: 'portfolio-f4327.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );
}
